;;; uptimes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uptimes.el

(autoload 'uptimes-save "uptimes" "\
Write the uptimes to `uptimes-database'." t)
(autoload 'uptimes "uptimes" "\
Display the last and top `uptimes-keep-count' uptimes." t)
(autoload 'uptimes-current "uptimes" "\
Display the uptime for the current Emacs session." t)
(register-definition-prefixes "uptimes" '("uptimes-"))

;;; End of scraped data

(provide 'uptimes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uptimes-autoloads.el ends here
