;;; nix-sandbox-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nix-sandbox.el

(autoload 'nix-shell-command "nix-sandbox" "\
Assemble a command from ARGS that can be executed in the specified SANDBOX.

(fn SANDBOX &rest ARGS)")
(autoload 'nix-compile "nix-sandbox" "\
Compile a program using the given COMMAND in SANDBOX.

(fn SANDBOX &rest COMMAND)" t)
(autoload 'nix-sandbox/nix-shell "nix-sandbox" "\
Run a COMMAND in the given SANDBOX and return the output.

(fn SANDBOX &rest COMMAND)")
(autoload 'nix-exec-path "nix-sandbox" "\
Return the `exec-path' of the given SANDBOX.

(fn SANDBOX)")
(autoload 'nix-executable-find "nix-sandbox" "\
Search for an EXECUTABLE in the given SANDBOX.

(fn SANDBOX EXECUTABLE)")
(autoload 'nix-find-sandbox "nix-sandbox" "\
Search for a sandbox starting at PATH traversing upwards the directory tree.
If the directory contains a `shell.nix' file, the path to this
file is returned.  Otherwise if the directory contains a
`default.nix' file, the parent directory is returned.

(fn PATH)")
(autoload 'nix-current-sandbox "nix-sandbox" "\
Return the path of the sandbox that is closest to the current working directory.")
(register-definition-prefixes "nix-sandbox" '("nix-"))

;;; End of scraped data

(provide 'nix-sandbox-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nix-sandbox-autoloads.el ends here
